// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/api/album.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination ./pkg/api/mocks/mock_album.go -source ./pkg/api/album.go
//

// Package mocks is a generated GoMock package.
package mocks
